### ISSUE TITLE
apps/guetzli: batch compress

### ISSUE THREAD

**Issue by chai2010** [chai2010/guetzli-go#1]
```
guetzli input_dir output_dir *.png
guetzli -regexp="^(a|b)\d+" input_dir output_dir *.png
```

**Comment by abcfy2** [comment]
Would you plan to support output dir keep the same structure as the input dir? Or support output the compressed jpg images to input dir(could override the exist image)?

**Comment by chai2010** [comment]
yes, the output dir has the same struct as the input dir.
and if the output path is the input path, it will override the exist image.

**Comment by chai2010** [comment]
fixed in https://github.com/chai2010/guetzli-go/commit/9628206f37321a0d19b4752965ed89874f19abbd, https://github.com/chai2010/guetzli-go/commit/d1ee93c814ab2d8e05c9db34b05a9a8e8e93dd68

**Comment by chai2010** [comment]
update in https://github.com/chai2010/guetzli-go/commit/ba6472252a14d1b78ba78a28b850c0baf84c074b

**Comment by chai2010** [comment]
https://github.com/google/guetzli/issues/80
